### ISSUE TITLE
How to include custom layout design 

### ISSUE THREAD

**Issue by mkamals1989** [blazsolar/HorizontalPicker#64]
Hi,

Please tell me how to implement custom layout for the items in this lib.

Thanks in Advance.

**Comment by blazsolar** [comment]
That is not possible with this library as it only supports text. I would recommend that you take a look into `RecyclerView` in combination with [PagerSnapHelper](https://developer.android.com/reference/android/support/v7/widget/PagerSnapHelper.html). You can achieve similar effect with layouts instead of text items.
